id: synthetic.ticks  # format: provider.dataset

parser:
  entrypoint: "core.synthetic.ticks"
  args: {}
loader:
  entrypoint: "core.synthetic.ticks"
  args:
    start: "${start_time}"
    end: "${end_time}"
    frequency: "1h"
